# Generated by Django 6.0.5 on 2026-06-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together={('sub_department', 'month', 'year')},
        ),
    ]
